In [8]:
list_one = list(range(1,4))
list_two = list(range(1,4))
sum = []
for i in range(3):
    list_one[i] = list_one[i] ** 2
    list_two[i] = list_two[i] ** 3
    sum.append(list_one[i] + list_two[i])
print(sum)    
    
    

[2, 12, 36]


In [9]:
import numpy as np
array_one = np.arange(1,4) ** 2
array_two = np.arange(1,4) ** 3
print(array_one+array_two)

[ 2 12 36]


# Creating NumPy Arrays


## From a Python List

In [10]:
my_list = [1,2,3]
my_list
np.array(my_list)

array([1, 2, 3])

In [12]:
my_list1 = [1,2,3]
my_list2 = [4,5,6]
my_list3 = [7,8,9]
multi_array = np.array([my_list1,my_list2,my_list3])
multi_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in-Methods


#### arrange

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### linspace
Return evenly spaced numbers over a specified interval.

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [16]:
np.random.rand(4,3)

array([[0.39033899, 0.82462097, 0.59970323],
       [0.86966344, 0.85828531, 0.89099005],
       [0.97363286, 0.60406964, 0.25764459],
       [0.61709095, 0.132692  , 0.27242359]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(2)

array([-1.72313503, -0.69377314])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [18]:
np.random.randint(1,50,5)

array([39,  6,  2, 39, 30])

In [28]:
arr = np.arange(1,26)

In [29]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr.shape

(25,)

In [31]:
arr.reshape(25,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [33]:
arr.dtype

dtype('int32')