# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np
arr = np.random.randint(1,50,10)
arr

array([47, 16, 23, 28, 32,  9, 31, 44, 30, 48])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
arr[4]

32

In [5]:
arr[0:4]

array([47, 16, 23, 28])

In [12]:
arr[:5]

array([10, 10, 10, 28, 32])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [7]:
arr[0:3] = 10
arr

array([10, 10, 10, 28, 32,  9, 31, 44, 30, 48])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [8]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
arr_2d[1]

array([20, 25, 30])

In [10]:
arr_2d[1,2]

30

In [11]:
arr_2d[0,2]

15

In [15]:
arr_2d[0,1:3]

array([10, 15])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [16]:
import numpy as np
arr = np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [21]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [22]:
np.max(arr)

9

In [23]:
np.log(arr)

<ipython-input-23-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])